In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("fake_or_real_news.csv")

In [12]:
df.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [13]:
df.shape

(6335, 4)

In [14]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6335 non-null   int64
 1   title       6335 non-null   object
 2   text        6335 non-null   object
 3   label       6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB

In [16]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df["label"].value_counts()

label
REAL    3171
FAKE    3164
Name: count, dtype: int64

In [19]:
df.describe()

         Unnamed: 0
count   6335.000000
mean    5280.415627
std     3038.503953
min        2.000000
25%     2674.500000
50%     5271.000000
75%     7901.000000
max    10557.000000

In [20]:
df.sample(5)

,Unnamed: 0,title,text,label
3038,1942,Hillary is new and improved! Take as directed.,A verdict in 2017 could have sweeping conseque...,REAL
610,10300,"India's Stonehenge: 7,000-Year-Old Megalithic ...",Print Email http://humansarefree.com/2016/10/i...,FAKE
1425,9663,Tony Blair suggests a second referendum to rev...,Politics Former British Prime Minister Tony Bl...,FAKE
2003,685,"Bernie Sanders, Hillary Clinton battle for Cal...",San Diego (CNN) Hillary Clinton is back in the...,REAL
5220,7987,A Martian Looks at Election Day,by Lambert Strether \nBy Lambert Strether of C...,FAKE

In [21]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [22]:
df.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [23]:
df.dropna(inplace=True)

In [24]:
df["label"] = df["label"].map({"FAKE":0, "REAL":1})

In [25]:
import re
import string
import nltk

In [26]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [27]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [28]:
def clean_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove extra spaces
    text = text.strip()

    return text

In [29]:
df["text"] = df["text"].apply(clean_text)

In [30]:
def remove_stopwords(text):

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

In [31]:
df["text"] = df["text"].apply(remove_stopwords)

In [32]:
df.head()

,title,text,label
0,You Can Smell Hillary’s Fear,daniel greenfield shillman journalism fellow f...,0
1,Watch The Exact Moment Paul Ryan Committed Pol...,google pinterest digg linkedin reddit stumbleu...,0
2,Kerry to go to Paris in gesture of sympathy,us secretary state john f kerry said monday st...,1
3,Bernie supporters on Twitter erupt in anger ag...,— kaydee king kaydeeking november lesson tonig...,0
4,The Battle of New York: Why This Primary Matters,primary day new york frontrunners hillary clin...,1

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
vectorizer = TfidfVectorizer()

In [35]:
X = vectorizer.fit_transform(df["text"])

In [36]:
X = vectorizer.fit_transform(df["text"])

In [37]:
y = df["label"]

In [38]:
print(X.shape)
print(y.shape)

(6335, 79162)
(6335,)

In [39]:
print(vectorizer.get_feature_names_out()[:20])

['aa' 'aaa' 'aaaa' 'aaaaadd' 'aaaasetlayoutnew' 'aaas' 'aab' 'aachen'
 'aadhar' 'aadmi' 'aae' 'aahing' 'aaib' 'aaj' 'aakar' 'aakhri' 'aalia'
 'aaliya' 'aall' 'aam']

In [40]:
print(X[0])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 446 stored elements and shape (1, 79162)>
  Coords	Values
  (0, 16256)	0.029353735959691752
  (0, 28697)	0.038853617149471865
  (0, 63278)	0.04390633473728365
  (0, 36599)	0.027074281142725008
  (0, 24396)	0.020679327788979157
  (0, 26259)	0.01934365158106785
  (0, 10899)	0.016776000127455382
  (0, 46699)	0.027144928591678674
  (0, 78225)	0.02954614887888917
  (0, 77681)	0.024823963679325364
  (0, 25542)	0.02536978088978999
  (0, 56274)	0.022894805271527176
  (0, 35522)	0.024795168224696934
  (0, 24789)	0.03741685180804556
  (0, 67104)	0.05689543369153294
  (0, 21071)	0.048891542700492584
  (0, 31168)	0.20304079688702573
  (0, 59659)	0.02861740152721428
  (0, 12360)	0.17491538671648732
  (0, 28172)	0.08078900268606098
  (0, 75748)	0.07090448961257749
  (0, 24188)	0.5660741215111055
  (0, 77416)	0.020049536918891157
  (0, 73595)	0.09335831407917539
  (0, 70248)	0.02720610376349462
  :	:
  (0, 62507)	0.018269243290700284
  (0, 74457)	0.02370429435914931
  (0, 10267)	0.03179014183028851
  (0, 66491)	0.019730974426643767
  (0, 5048)	0.014594067157246015
  (0, 12499)	0.025401748034565422
  (0, 56572)	0.027866725559915144
  (0, 72579)	0.02771834933402706
  (0, 61332)	0.023775447824189486
  (0, 42375)	0.011275094255881187
  (0, 38745)	0.010801267766287363
  (0, 66229)	0.01823417597359792
  (0, 77579)	0.029486617498761435
  (0, 48113)	0.023945132505637297
  (0, 16020)	0.022814007972103364
  (0, 63105)	0.020297971590937408
  (0, 46681)	0.013314126782323249
  (0, 63541)	0.02134415964958017
  (0, 11138)	0.020184788932809016
  (0, 39703)	0.022082688835133646
  (0, 9363)	0.03028089625106767
  (0, 32615)	0.0266563298834703
  (0, 137)	0.0266563298834703
  (0, 8786)	0.017961387520535017
  (0, 21276)	0.01806210843995718

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [43]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5068, 79162)
(1267, 79162)
(5068,)
(1267,)

In [44]:
model = LogisticRegression(max_iter=1000)

In [45]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [46]:
y_pred = model.predict(X_test)

In [47]:
print("Actual:", y_test.iloc[:10].values)
print("Predicted:", y_pred[:10])

Actual: [0 0 0 0 0 0 1 0 1 0]
Predicted: [0 0 0 0 0 0 1 0 1 0]

In [48]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [49]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9210734017363852

In [50]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[593  35]
 [ 65 574]]

In [51]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       628
           1       0.94      0.90      0.92       639

    accuracy                           0.92      1267
   macro avg       0.92      0.92      0.92      1267
weighted avg       0.92      0.92      0.92      1267

In [52]:
news = [
    "The government announced a new education policy today."
]

news_vector = vectorizer.transform(news)

prediction = model.predict(news_vector)

print(prediction)

[0]

In [54]:
import pandas as pd

cm_df = pd.DataFrame(
    cm,
    index=["Actual Fake", "Actual Real"],
    columns=["Predicted Fake", "Predicted Real"]
)

print(cm_df)

             Predicted Fake  Predicted Real
Actual Fake             593              35
Actual Real              65             574